language: python
python:
  - 2.7
  - 3.3
before_install:
  - pip install pygments
  - pip install tabulate
install:
  - python setup.py install
script:
  - cd examples/project1 && ./testrunner.py -S moda --debug
notifications:
  email: false
