language: python
python:
  - 2.7
  - 3.3
before_install:
  - pip install "pygments=1.6"
  - pip install "tabulate=0.6"
install:
  - python setup.py install
script:
  - cd examples/project1 && ./testrunner.py -S moda --debug
notifications:
  email: false
