language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - "pypy"
before_install:
  - pip install pygments
  - pip install tabulate
install:
  - python setup.py install
script:
  - cd examples/project1
  - ./testrunner.py -S moda -L
  - ./testrunner.py -S moda
  - ./testrunner.py -S moda --debug
  - cd ../../tests
  - ./test_logger.py
notifications:
  email: false
